GEWIS/aurora-core

src/modules/modes/centurion/tapes/athena-centurion.ts
src/modules/modes/centurion/tapes/index.ts

Fixed athena centurion

---

src/helpers/security-groups.ts
src/modules/handlers/screen/centurion-screen-handler.ts
src/modules/handlers/screen/time-trail-race-screen-handler.ts
src/modules/modes/centurion/centurion-controller.ts
src/modules/modes/mode-controller.ts
src/modules/modes/mode-settings.ts
src/modules/modes/time-trail-race/time-trail-race-controller.ts
src/modules/server-settings/server-settings-store.ts
src/modules/sudosos/sudosos-controller.ts
src/modules/sudosos/sudosos-service.ts
src/modules/sudosos/sudosos-settings.ts

feat(settings): improve server settings to make them compatible with the backoffice

---

src/helpers/security-groups.ts
src/modules/handlers/screen/poster/poster-screen-controller.ts

There were a few routes that were restricted for screen subscribers but should have been available.

fix(auth): fix screen subscriber issues

---

src/helpers/security-groups.ts
src/modules/handlers/screen/centurion-screen-handler.ts
src/modules/handlers/screen/curently-playing-track-handler.ts
src/modules/handlers/screen/index.ts
src/modules/handlers/screen/poster/index.ts
src/modules/handlers/screen/poster/poster-screen-controller.ts
src/modules/handlers/screen/poster/poster-screen-handler.ts
src/modules/handlers/screen/room-responsible-legacy-controller.ts
src/modules/handlers/screen/room-responsible-legacy-handler.ts
src/modules/handlers/screen/screen-handler-settings.ts
src/modules/root/handler-factory.ts
src/modules/server-settings/server-setting.ts

feat(room-responsible): add legacy room responsible handler

---

src/modules/lights/effects/color/sparkle.ts
src/modules/modes/centurion/centurion-mode.ts
src/modules/modes/centurion/tapes/gebroeders-scooter-centurion.ts

feat(lights-sparkle): make sparkle effect permutation-based

---

src/helpers/security-groups.ts
src/modules/handlers/screen/centurion-screen-handler.ts
src/modules/handlers/screen/curently-playing-track-handler.ts
src/modules/handlers/screen/index.ts
src/modules/handlers/screen/poster/index.ts
src/modules/handlers/screen/poster/poster-screen-controller.ts
src/modules/handlers/screen/poster/poster-screen-handler.ts
src/modules/handlers/screen/room-responsible-legacy-controller.ts
src/modules/handlers/screen/room-responsible-legacy-handler.ts
src/modules/handlers/screen/screen-handler-settings.ts
src/modules/handlers/screen/time-trail-race-screen-handler.ts
src/modules/lights/effects/color/sparkle.ts
src/modules/modes/centurion/centurion-controller.ts
src/modules/modes/centurion/centurion-mode.ts
src/modules/modes/centurion/tapes/gebroeders-scooter-centurion.ts
src/modules/modes/centurion/tapes/mix-tape.ts
src/modules/modes/mode-controller.ts
src/modules/modes/mode-settings.ts
src/modules/modes/time-trail-race/time-trail-race-controller.ts
src/modules/root/handler-factory.ts
src/modules/server-settings/server-setting.ts
src/modules/server-settings/server-settings-store.ts
src/modules/sudosos/sudosos-controller.ts
src/modules/sudosos/sudosos-service.ts
src/modules/sudosos/sudosos-settings.ts

Includes various fixes and improvements for the GEWIS Centurion Marathon of 2024.

Aurora release for Centurion Marathon 2024

---

src/modules/lights/entities/lights-moving-head-wheel.ts
src/seed/seed.ts

These are Hubble's old moving heads. They are not yet added to a group, because that should be determined later when they are installed in the GEWIS room.

feat: add Showtec Kanjo Spot 10

---

src/modules/handlers/screen/index.ts
src/modules/handlers/screen/poster/hubble/hubble-closed-poster-screen-handler.ts
src/modules/handlers/screen/poster/hubble/hubble-lastcall-poster-screen-handler.ts
src/modules/root/handler-factory.ts

Adds other Hubble posters, namely closed and last call
The handlers are just empty classes, not the most pretty but I couldn't find another way to make this work

feat(poster): Add other Hubble poster handlers

---

src/modules/spotify/spotify-api-handler.ts
src/modules/spotify/spotify-controller.ts

Fix some missing endpoint return objects and add a new endpoint to switch the currently active Spotify user. The latter will probably never be used, but Aurora should support this, so why not implement it to make the feature set complete.

feat(spotify): improve and add endpoints to support Backoffice

---

openapi-ts.config.ts
package.json
yarn.lock

- Style _(Change that do not affect the functionality of the code)_

chore(deps): revert removal of @hey-api/openapi-ts

---

src/modules/auth/api-key-middleware.ts

Conform to https://nodejs.org/api/http.html#messageheaders the headers should be lower case. Tested on my machine and it works now

fix(auth): header check is now lower case, conform to the spec

---

src/modules/lights/color-definitions.ts

Adds a new color, namely mint, which is green with a slight tone of blue. This expands the set of green-like colors in the current palette.
Depends on https://github.com/GEWIS/aurora-core/issues/93.

feat(colors): add new mint color

---

src/modules/beats/artificial-beat-generator.ts
src/modules/beats/beat-generator-controller.ts
src/modules/beats/index.ts
src/modules/beats/simple-beat-generator.ts
src/modules/handlers/lights/develop-effects-handler.ts
src/modules/modes/centurion/centurion-mode.ts
src/modules/modes/time-trail-race/time-trail-race-mode.ts

The debug page in backoffice constantly refreshes because the Real Time Beat Detector is being recreated (deleted and added) every time the bpm changes. Works great, if you do not send an update to all backoffice instances every time you do something like this.

fix(beats): fix constant recreation of real time beat detector

---

src/error.ts
src/helpers/custom-error.ts

fix: HTTP error responses always including status 401 in body

---

src/modules/auth/authentication.ts

Fix internal server error
This PR fixes a bug I found where when an endpoint is only accessible by an integration user and a normal, logged-in users tries to access it, the server throws an error.

fix(authentication): fix integration user endpoint interal server error

---

.env.example

Small changes to .env.example to be consistent with the readme and default setup of Aurora Backoffice.
- Chore

chore: change .env.example to be consistent with readme and backoffice

---

src/helpers/security-groups.ts
src/modules/root/root-lights-controller.ts

Fixes a 403 error when a screen subscriber is trying to fetch Aurora color definitions. While I was at it, I also made the endpoint accessible to integration users as well.

feat(colors): make color definitions API endpoint more broadly accessible

---

src/helpers/transformers.ts
src/modules/auth/endpoint-security.ts
src/modules/auth/integration/README.md
src/modules/auth/integration/entities/integration-user.ts
src/modules/lights/entities/lights-fixture.ts
src/modules/lights/entities/scenes/lights-predefined-effect.ts
src/modules/root/entities/subscribe-entity.ts
src/modules/server-settings/server-setting.ts
src/modules/timed-events/entities/timed-event.ts
tsoa.json

chore: process comments on release PR

---

Dockerfile

- CI/CD _(Changes to the CI/CD configuration)_

ci: fix python missing in Docker image

---

src/helpers/transformers.ts

Hotfix because this issue block deployment.

fix: writing null to DB if default setting evaluates to false

---

docker-compose.yml

Update the compose with the new volumes and also use the new github CR images.
- Documentation improvement
- CI/CD _(Changes to the CI/CD configuration)_

ci(docker): update compose to reflect new directories and images

---

src/modules/modes/centurion/tapes/gebroeders-scooter-totale-escalatien.ts

Gebroeders Scooter - Totale EscalaTIEN now has custom bpm values for each song. I even added the GEWIScobal for a certain song because it felt appropriate.

fix(centurion): fix incorrect BPM in Gebroeders Scooter Totale Escalatien

---

.github/workflows/validate.yaml
docker-compose.yml
package.json
src/helpers/security-groups.ts
src/modules/modes/centurion/tapes/gebroeders-scooter-totale-escalatien.ts
src/modules/modes/centurion/tapes/index.ts
src/modules/root/entities/screen.ts
src/modules/root/handler-controller.ts
src/modules/root/root-screen-controller.ts
src/modules/root/root-screen-service.ts
src/seed/seed.ts
src/validate.ts
yarn.lock

Primarily title, but also includes dependency updates and fixes to the `docker-compose.yml` file.
- Style _(Change that do not affect the functionality of the code)_
- CI/CD _(Changes to the CI/CD configuration)_

release: add scaling factor to screen entities to support 4K displays

---

src/modules/auth/integration/entities/integration-user.ts

fix: GET integration users trying to parse date to JSON

---

src/modules/orders/order-controller.ts

very simple, needed to allow kitchen staff to remove orders from the screens via food.hubble.cafe

feat(order): allow integration users to delete orders

---

src/modules/lights/entities/movement.ts

fix(lights): relative base pan column being int instead of float (again)
